"""Narrow persistence contract for the durable Job catalog."""

from typing import Protocol

from .model import (Finding, FindingEvidence, FindingKind, Job, JobRun, JobRunStatus,
                    JobSchedule, JobTarget, JobTrigger, JobTriggerType)


class JobStore(Protocol):
    def create_job(self, name: str, description: str = "", *, enabled: bool = True,
                   target: JobTarget | None = None) -> Job: ...
    def get_job(self, job_id: int) -> Job | None: ...
    def list_jobs(self, *, target: JobTarget | None = None) -> tuple[Job, ...]: ...
    def set_job_description(self, job_id: int, description: str) -> Job: ...
    def set_job_enabled(self, job_id: int, enabled: bool) -> Job: ...
    def set_schedule(self, job_id: int, local_time: str, timezone: str, *, enabled: bool = True) -> JobSchedule: ...
    def get_schedule(self, job_id: int) -> JobSchedule | None: ...
    def list_schedules(self) -> tuple[JobSchedule, ...]: ...
    def remove_schedule(self, job_id: int) -> bool: ...
    def set_trigger(self, job_id: int, event_type: JobTriggerType, *, enabled: bool = True) -> JobTrigger: ...
    def get_trigger(self, job_id: int, event_type: JobTriggerType) -> JobTrigger | None: ...
    def list_triggers(self, event_type: JobTriggerType | None = None) -> tuple[JobTrigger, ...]: ...
    def remove_trigger(self, job_id: int, event_type: JobTriggerType) -> bool: ...
    def create_triggered_run(self, job_id: int) -> JobRun | None: ...
    def create_scheduled_run(self, job_id: int, local_date: str) -> JobRun | None: ...
    def create_run(self, job_id: int) -> JobRun: ...
    def get_run(self, run_id: int) -> JobRun | None: ...
    def list_runs(self, job_id: int) -> tuple[JobRun, ...]: ...
    def get_latest_completed_run(self, job_id: int) -> JobRun | None: ...
    def interrupt_nonterminal_runs(self) -> tuple[JobRun, ...]: ...
    def transition_run(self, run_id: int, status: JobRunStatus, *,
                       outcome_summary: str | None = None,
                       error_summary: str | None = None,
                       result_report: str | None = None) -> JobRun: ...
    def create_finding(self, job_id: int, run_id: int, task_id: str, episode_id: int,
                       topic: str, kind: FindingKind, claim: str,
                       evidence_basis: tuple[FindingEvidence, ...]) -> Finding: ...
    def get_finding(self, finding_id: int) -> Finding | None: ...
    def list_findings(self, *, limit: int = 20) -> tuple[Finding, ...]: ...
    def search_findings(self, query: str, *, limit: int = 5) -> tuple[Finding, ...]: ...
    def close(self) -> None: ...
