"""Narrow persistence contract for the durable Job catalog."""

from typing import Protocol

from .model import Job, JobRun, JobRunStatus, JobSchedule, JobTarget


class JobStore(Protocol):
    def create_job(self, name: str, description: str = "", *, enabled: bool = True,
                   target: JobTarget | None = None) -> Job: ...
    def get_job(self, job_id: int) -> Job | None: ...
    def list_jobs(self, *, target: JobTarget | None = None) -> tuple[Job, ...]: ...
    def set_job_description(self, job_id: int, description: str) -> Job: ...
    def set_job_enabled(self, job_id: int, enabled: bool) -> Job: ...
    def set_schedule(self, job_id: int, local_time: str, timezone: str, *, enabled: bool = True) -> JobSchedule: ...
    def get_schedule(self, job_id: int) -> JobSchedule | None: ...
    def list_schedules(self) -> tuple[JobSchedule, ...]: ...
    def remove_schedule(self, job_id: int) -> bool: ...
    def create_scheduled_run(self, job_id: int, local_date: str) -> JobRun | None: ...
    def create_run(self, job_id: int) -> JobRun: ...
    def get_run(self, run_id: int) -> JobRun | None: ...
    def list_runs(self, job_id: int) -> tuple[JobRun, ...]: ...
    def get_latest_completed_run(self, job_id: int) -> JobRun | None: ...
    def transition_run(self, run_id: int, status: JobRunStatus, *,
                       outcome_summary: str | None = None,
                       error_summary: str | None = None,
                       result_report: str | None = None) -> JobRun: ...
    def close(self) -> None: ...
